-- STREAMS - Real-time data processing 
-- IT STORES THE CHANGES MADE TO A TABLE IN A STREAM OBJECT, WHICH CAN BE CONSUMED BY OTHER OBJECTS LIKE TASKS OR PIPELINES.
-- IT WILL RETURN TRUE IF THERE ARE CHANGES IN THE STREAM OBJECT, OTHERWISE FALSE.

USE DATABASE CLIMATE_ENERGY_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE STREAM RAW_ENERGY_STREAM
ON TABLE RAW_ENERGY_DATA;

SHOW STREAMS;

SELECT *
FROM RAW_ENERGY_STREAM;

SELECT COUNT(*)
FROM RAW_ENERGY_STREAM;

INSERT INTO RAW_ENERGY_DATA
(
    "country",
    "year",
    "population",
    "gdp"
)
VALUES
(
    'TEST_COUNTRY',
    2026,
    1000000,
    500000000
);

SELECT *
FROM RAW_ENERGY_STREAM;

SELECT SYSTEM$STREAM_HAS_DATA('RAW_ENERGY_STREAM');
